from enum import Enum


class Currency(Enum):
    # FIXME: every member below (AED through ZWL, except ZWL itself) is defined with a trailing
    # comma, e.g. `AED = 1,` — this makes `.value` a 1-element tuple like (1,) instead of an int.
    # `Currency.CNY.value == 34` is False; it's `(34,)`. Remove all the trailing commas.
    UNKNOWN = 0
    AED = 1,  # UAE Dirham
    AFN = 2,  # Afghani
    ALL = 3,  # Lek
    AMD = 4,  # Armenian Dram
    ANG = 5,  # Netherlands Antillean Guilder
    AOA = 6,  # Kwanza
    ARS = 7,  # Argentine Peso
    AUD = 8,  # Australian Dollar
    AWG = 9,  # Aruban Florin
    AZN = 10,  # Azerbaijan Manat
    BAM = 11,  # Convertible Mark
    BBD = 12,  # Barbados Dollar
    BDT = 13,  # Taka
    BGN = 14,  # Bulgarian Lev
    BHD = 15,  # Bahraini Dinar
    BIF = 16,  # Burundi Franc
    BMD = 17,  # Bermudian Dollar
    BND = 18,  # Brunei Dollar
    BOB = 19,  # Boliviano
    BOV = 20,  # Mvdol
    BRL = 21,  # Brazilian Real
    BSD = 22,  # Bahamian Dollar
    BTN = 23,  # Ngultrum
    BWP = 24,  # Pula
    BYN = 25,  # Belarusian Ruble
    BZD = 26,  # Belize Dollar
    CAD = 27,  # Canadian Dollar
    CDF = 28,  # Congolese Franc
    CHE = 29,  # WIR Euro
    CHF = 30,  # Swiss Franc
    CHW = 31,  # WIR Franc
    CLF = 32,  # Unidad de Fomento
    CLP = 33,  # Chilean Peso
    CNY = 34,  # Chinese Yuan, Renminbi
    COP = 35,  # Colombian Peso
    COU = 36,  # Unidad de Valor Real
    CRC = 37,  # Costa Rican Colon
    CUC = 38,  # Peso Convertible
    CUP = 39,  # Cuban Peso
    CVE = 40,  # Cabo Verde Escudo
    CZK = 41,  # Czech Koruna
    DJF = 42,  # Djibouti Franc
    DKK = 43,  # Danish Krone
    DOP = 44,  # Dominican Peso
    DZD = 45,  # Algerian Dinar
    EGP = 46,  # Egyptian Pound
    ERN = 47,  # Nakfa
    ETB = 48,  # Ethiopian Birr
    EUR = 49,  # Euro
    FJD = 50,  # Fiji Dollar
    FKP = 51,  # Falkland Islands Pound
    GBP = 52,  # Pound Sterling
    GEL = 53,  # Lari
    GHS = 54,  # Ghana Cedi
    GIP = 55,  # Gibraltar Pound
    GMD = 56,  # Dalasi
    GNF = 57,  # Guinean Franc
    GTQ = 58,  # Quetzal
    GYD = 59,  # Guyana Dollar
    HNL = 60,  # Lempira
    HKD = 61,  # Hong Kong Dollar
    HRK = 62,  # Kuna (Euro adopted in 2023)
    HTG = 63,  # Gourde
    HUF = 64,  # Forint
    IDR = 65,  # Rupiah
    ILS = 66,  # New Israeli Sheqel
    INR = 67,  # Indian Rupee
    IQD = 68,  # Iraqi Dinar
    IRR = 69,  # Iranian Rial
    ISK = 70,  # Iceland Krona
    JMD = 71,  # Jamaican Dollar
    JOD = 72,  # Jordanian Dinar
    JPY = 73,  # Japenses Yen
    KES = 74,  # Kenyan Shilling
    KGS = 75,  # Som
    KHR = 76,  # Riel
    KMF = 77,  # Comorian Franc
    KPW = 78,  # North Korean Won
    KRW = 79,  # Won
    KWD = 80,  # Kuwaiti Dinar
    KYD = 81,  # Cayman Islands Dollar
    KZT = 82,  # Tenge
    LAK = 83,  # Kip
    LBP = 84,  # Lebanese Pound
    LKR = 85,  # Sri Lanka Rupee
    LRD = 86,  # Liberian Dollar
    LSL = 87,  # Loti
    LYD = 88,  # Libyan Dinar
    MAD = 89,  # Moroccan Dirham
    MDL = 90,  # Moldovan Leu
    MGA = 91,  # Malagasy Ariary
    MKD = 92,  # Denar
    MMK = 93,  # Kyat
    MNT = 94,  # Tugrik
    MOP = 95,  # Pataca
    MRU = 96,  # Ouguiya
    MUR = 97,  # Mauritius Rupee
    MVR = 98,  # Rufiyaa
    MWK = 99,  # Malawi Kwacha
    MXN = 100,  # Mexican Peso
    MXV = 101,  # Mexican Unidad de Inversion (UDI)
    MYR = 102,  # Malaysian Ringgit
    MZN = 103,  # Mozambique Metical
    NAD = 104,  # Namibia Dollar
    NGN = 105,  # Naira
    NIO = 106,  # Cordoba Oro
    NOK = 107,  # Norwegian Krone
    NPR = 108,  # Nepalese Rupee
    NZD = 109,  # New Zealand Dollar
    OMR = 110,  # Rial Omani
    PAB = 111,  # Balboa
    PEN = 112,  # Sol
    PGK = 113,  # Kina
    PHP = 114,  # Philippine Peso
    PKR = 115,  # Pakistan Rupee
    PLN = 116,  # Zloty
    PYG = 117,  # Guarani
    QAR = 118,  # Qatari Rial
    RON = 119,  # Romanian Leu
    RSD = 120,  # Serbian Dinar
    RUB = 121,  # Russian Ruble
    RWF = 122,  # Rwanda Franc
    SAR = 123,  # Saudi Riyal
    SBD = 124,  # Solomon Islands Dollar
    SCR = 125,  # Seychelles Rupee
    SDG = 126,  # Sudanese Pound
    SEK = 127,  # Swedish Krona
    SGD = 128,  # Singapore Dollar
    SHP = 129,  # Saint Helena Pound
    SLE = 130,  # Leone
    SOS = 131,  # Somali Shilling
    SRD = 132,  # Surinam Dollar
    SSP = 133,  # South Sudanese Pound
    STN = 134,  # Dobra
    SVC = 135,  # El Salvador Colon (historic)
    SYP = 136,  # Syrian Pound
    SZL = 137,  # Lilangeni
    THB = 138,  # Baht
    TJS = 139,  # Somoni
    TMT = 140,  # Turkmenistan New Manat
    TND = 141,  # Tunisian Dinar
    TOP = 142,  # Pa’anga
    TRY = 143,  # Turkish Lira
    TTD = 144,  # Trinidad and Tobago Dollar
    TWD = 145,  # New Taiwan Dollar
    TZS = 146,  # Tanzanian Shilling
    UAH = 147,  # Hryvnia
    UGX = 148,  # Uganda Shilling
    USD = 149,  # US Dollar
    UYI = 150,  # Uruguay Peso en Unidades Indexadas
    UYU = 151,  # Peso Uruguayo
    UZS = 152,  # Uzbekistan Sum
    VED = 153,  # Venezuelan Bolívar (new)
    VES = 154,  # Venezuelan Bolívar Soberano
    VND = 155,  # Dong
    VUV = 156,  # Vatu
    WST = 157,  # Tala
    XAF = 158,  # CFA Franc BEAC
    XCD = 159,  # East Caribbean Dollar
    XDR = 160,  # IMF Special Drawing Right
    XOF = 161,  # CFA Franc BCEAO
    XPF = 162,  # CFP Franc
    YER = 163,  # Yemeni Rial
    ZAR = 164,  # Rand
    ZMW = 165,  # Zambian Kwacha
    ZWL = 166  # Zimbabwe Dollar
