name: Python CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --frozen  # ignores the pyproject.toml, purely dependent on uv.lock file as the absolute source of truth

    - name: Run tests
      run: uv run pytest tests/
